---
- name: Add user's group
  group: name={{ user[item]['name'] }} gid={{ user[item]['gid'] }}
  sudo: yes
  with_flattened: accounts
  when: user[item]['enabled']

- name: Add user
  user: name={{ user[item]['name'] }} group={{ user[item]['name'] }} shell=/bin/bash uid={{ user[item]['uid'] }}
  sudo: yes
  with_flattened: accounts
  when: user[item]['enabled']

- name: Add SSH key
  authorized_key: user={{ user[item]['name'] }} key='{{ user[item]['ssh_key'] }}' state=present
  sudo: yes
  with_flattened: accounts
  when: user[item]['enabled']

- name: Remove SSH key
  authorized_key: user={{ user[item]['name'] }} key='{{ user[item]['ssh_key'] }}' state=absent
  sudo: yes
  with_flattened: accounts
  when: not user[item]['enabled']
  ignore_errors: yes

- name: Remove user
  user: name={{ user[item]['name'] }} state=absent
  sudo: yes
  with_flattened: accounts
  when: not user[item]['enabled']
